# Generated by Django 2.0 on 2019-04-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emo_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsId', models.CharField(default='', max_length=20)),
                ('productTitle', models.CharField(default='', max_length=512)),
                ('storeId', models.CharField(default='', max_length=32)),
                ('storeName', models.CharField(default='', max_length=128)),
                ('new', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='ages',
            field=models.CharField(default='', max_length=20),
        ),
    ]
