# Generated by Django 2.0 on 2019-04-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_popular_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=20)),
                ('amount', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
