# Generated by Django 2.0 on 2019-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_price_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(default='', max_length=20)),
                ('productStatus', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
