# Generated by Django 2.0 on 2019-04-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_shop1_shop10_shop2_shop3_shop4_shop5_shop6_shop7_shop8_shop9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop1',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop10',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop3',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop4',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop5',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop6',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop7',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop8',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='shop9',
            name='productTitle',
            field=models.CharField(default='', max_length=512),
        ),
    ]
