# Generated by Django 2.0 on 2019-04-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20190419_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop10',
        ),
    ]
